# Generated by Django 2.2.1 on 2019-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.TextField(default='won'),
            preserve_default=False,
        ),
    ]
