# Generated by Django 2.2.1 on 2019-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_country_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='kprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
