# Generated by Django 2.2.1 on 2019-06-04 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_product_phit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.TextField()),
                ('r0', models.TextField()),
                ('r1', models.TextField()),
                ('r2', models.TextField()),
                ('r3', models.TextField()),
                ('r4', models.TextField()),
                ('r5', models.TextField()),
                ('r6', models.TextField()),
                ('r7', models.TextField()),
                ('r8', models.TextField()),
                ('r9', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Searchlog',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('pcode', models.TextField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
