# Generated by Django 2.2.1 on 2019-06-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_recommend_searchlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommend',
            old_name='r0',
            new_name='r_pcode',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r1',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r3',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r4',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r5',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r6',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r7',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r8',
        ),
        migrations.RemoveField(
            model_name='recommend',
            name='r9',
        ),
    ]
