# Generated by Django 2.2.1 on 2019-06-04 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190604_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='kprice',
        ),
    ]
