# Generated by Django 2.2.1 on 2019-05-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='short_cmane',
            new_name='short_cname',
        ),
    ]
