# Generated by Django 2.2.1 on 2019-05-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='short_cname',
            new_name='short_cmane',
        ),
    ]
