# Generated by Django 2.2.1 on 2019-05-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190519_1610'),
        ('app', '0002_favorite'),
    ]

    operations = [
    ]
