# Generated by Django 2.2.1 on 2019-05-21 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20190519_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
