# Generated by Django 2.2.1 on 2019-05-20 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20190520_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
