# Generated by Django 2.2.1 on 2019-05-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190516_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='short_cmane',
            new_name='short_cname',
        ),
    ]
