# Generated by Django 2.2.1 on 2019-05-18 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190516_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
