# Generated by Django 2.2.1 on 2019-05-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
