# Generated by Django 2.2.1 on 2019-05-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
