# Generated by Django 2.2.1 on 2019-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190522_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phit',
            field=models.BigIntegerField(default=0),
        ),
    ]
